//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLAP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveDirectoryUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActiveDirectoryUser()
        {
            this.ActiveDirectoryUser1 = new HashSet<ActiveDirectoryUser>();
        }
    
        public int ActiveDirectoryUserId { get; set; }
        public System.Guid Id { get; set; }
        public string userPrincipalName { get; set; }
        public string givenName { get; set; }
        public string displayName { get; set; }
        public Nullable<int> ManagerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveDirectoryUser> ActiveDirectoryUser1 { get; set; }
        public virtual ActiveDirectoryUser ActiveDirectoryUser2 { get; set; }
    }
}
