//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLAP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppraisalProcess()
        {
            this.PCAssociates = new HashSet<PCAssociate>();
            this.Peers = new HashSet<Peer>();
        }
    
        public int AppraisalProcessId { get; set; }
        public short AppraisalProcessYear { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> PeerListFinalizationByDate { get; set; }
        public Nullable<System.DateTime> SendPeerFeedbackRequestByDate { get; set; }
        public Nullable<System.DateTime> SendPeerFeedbackByDate { get; set; }
        public Nullable<System.DateTime> SelfAppraisalSubmissionByDate { get; set; }
        public Nullable<System.DateTime> AppraisalMeetingByDate { get; set; }
        public Nullable<System.DateTime> GoalSettingByDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCAssociate> PCAssociates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Peer> Peers { get; set; }
    }
}
