//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLAP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peer
    {
        public int PeerAssociateId { get; set; }
        public System.Guid AssociateUserId { get; set; }
        public System.Guid PeerUserId { get; set; }
        public Nullable<System.DateTime> LastNotificationDate { get; set; }
        public bool ShareFeedbackWithAssociate { get; set; }
        public string FeedbackDocumentUrl { get; set; }
        public int PCAssociateId { get; set; }
    
        public virtual PCAssociate PCAssociate { get; set; }
    }
}
